name: Ci Linters FastAPI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    - name: Install requirements
      run: pip install -r requirements.txt
      
    - name: Test with Black
      run: black --check --diff .

    - name: Test with Isort
      run: isort --check-only -diff --profile black .
      
    - name: Test with Pytest
      run: pytest -v
    
